/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Pane: typeof import('./src/components/SplitPane/pane.vue')['default']
    Resizer: typeof import('./src/components/SplitPane/resizer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitPane: typeof import('./src/components/SplitPane/index.vue')['default']
  }
}
